import React from "react";
import Head from "next/head";
import Navbar from "../components/navbar";
import DividerBar from "../components/divider";
import ContactUsHero from "../components/Hero/ContactUsHero";
import ContactForm from "../components/ContactForm";
import Footer from "../components/Footer";
import BottomBar from "../components/BottomBar";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import WorkTogather from "../components/WorkTogather";
import TopBar from "../components/TopBar";
const themeWebcodies = createTheme({
  palette: {
    background: {
      default: "#000000",
    },
    primary: {
      main: "#f5f5f5",
      dark: "#3250bf",
    },
    secondary: {
      main: "#d74a54",
    },
  },
  typography: {
    fontFamily: ["Poppins", "sans-serif"].join(","),
  },
});

function contactus() {
  return (
    <ThemeProvider theme={themeWebcodies}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <TopBar />
      <Navbar />
      <DividerBar />
      <ContactUsHero />
      <ContactForm />
      <WorkTogather />
      <Footer />
      <BottomBar />
    </ThemeProvider>
  );
}

export default contactus;
